
	</div>
	<div id="footer">
	  <div class="right">
	    generated in <?php echo round(microtime(true) - Krai::$STARTTIME, 3) ?>s
	  </div>
	  &nbsp;
	</div>
    </div>
    <div id="subfooter">
      <span style="float: right; padding-right: 5%;"><img src="<?php echo Krai::GetConfig("BASEURI") == "" ? "" : "/".Krai::GetConfig("BASEURI") ?>/images/krai-framework.png" alt="Krai Framework" /></span>
      <a href="mailto:<?php echo Krai::GetConfig("ADMIN_EMAIL") ?>">site admin</a>
    </div>
  </body>
</html>
